### ISSUE TITLE
Implement Support For DPDK

### ISSUE THREAD

**Issue by vkhitrin** [openstack-k8s-operators/edpm-ansible#299]
To have a similar parity to Tripleo Ansible roles for DPDK (https://github.com/openstack/tripleo-ansible/tree/e281ae7624774d71f22fbb993af967ed1ec08780/tripleo_ansible/roles/tripleo_ovs_dpdk/tasks), we would like to have the option to configure DPDK as part of EDPM.

The process for enabling DPDK:
1. Configure kernel arguments and huge pages (supported by `edpm-kernel` roles (but may be broken #298)
2. Enable DPDK `ovs-vsctl set Open_vSwitch . "other_config:dpdk-init=true"`, **missing natively, might be possible with `edpm_ovn_ovs_other_config`**.
3. Configure additional parameters for DPDK, such as lcores, pmds, memory.
4. Configure DPDK interfaces using `edpm_network_config`.

To spawn virtual machines using DPDK interfaces, we must also ensure that the vhostsocket directory is owned by the `hugetlbfs` group (currently in edpm, is set to `qemu`).

This issue is raised since there appears to be initial support for hardware offload initialization: https://github.com/openstack-k8s-operators/edpm-ansible/blob/7f96f9f5f69a0cf7cd354049c7e57d63b353b954/roles/edpm_ovn/tasks/configure.yml#L29-L39

**Comment by Jaganathancse** [comment]
yes edpm_ovn_ovs_other_config variable can be used.

**Comment by Jaganathancse** [comment]
Thanks Vadim for the updates. I am working on a patch to create new edpm-ansible role with custom naming and easy the NFV parameters configuration. Will let you know once done.

**Comment by nate-johnston** [comment]
@Jaganathancse You mentioned to me that DPDK testing was successful; can this issue be closed?

**Comment by Jaganathancse** [comment]
@nate-johnston ack. we can close this issue.

**Comment by Jaganathancse** [comment]
This issue is fixed.
https://github.com/openstack-k8s-operators/edpm-ansible/pull/328
